import { Location } from "./types";

// All locations below are DEMO DATA for testing the product experience.
// They are clearly marked isDemo: true and should be replaced with real
// verified partner locations before launch.
export const LOCATIONS: Location[] = [
  {
    id: "loc_1",
    slug: "registan",
    name: "BagDrop — Registan",
    city: "Samarkand",
    address: "Registan Square area, Samarkand",
    distanceLabel: "300m from Registan",
    description:
      "Located inside a verified souvenir shop directly facing Registan Square. The easiest drop-off point for anyone visiting the main ensemble — staff speak English and Russian.",
    pricePerBagPerDay: 30000,
    currency: "UZS",
    capacity: 30,
    availableBags: 18,
    maxBagsPerBooking: 6,
    hours: { open: "08:00", close: "22:00" },
    amenities: ["CCTV", "Verified partner", "Indoor storage", "QR check-in"],
    lat: 39.6542,
    lng: 66.9758,
    googleMapsUrl: "https://maps.google.com/?q=Registan+Samarkand",
    yandexMapsUrl: "https://yandex.com/maps/?text=Registan+Samarkand",
    partnerName: "Silk Road Souvenirs LLC",
    color: "#1f6f6b",
    isDemo: true,
    active: true,
  },
  {
    id: "loc_2",
    slug: "railway-station",
    name: "BagDrop — Railway Station",
    city: "Samarkand",
    address: "Next to Samarkand railway station",
    distanceLabel: "50m from the station entrance",
    description:
      "Ideal for travelers arriving by train who want to explore the city before checking into a hotel. Staffed around the clock.",
    pricePerBagPerDay: 25000,
    currency: "UZS",
    capacity: 50,
    availableBags: 22,
    maxBagsPerBooking: 8,
    hours: { open: "00:00", close: "23:59" },
    amenities: ["24/7", "CCTV", "Verified partner"],
    lat: 39.6975,
    lng: 66.9558,
    googleMapsUrl: "https://maps.google.com/?q=Samarkand+railway+station",
    yandexMapsUrl: "https://yandex.com/maps/?text=Samarkand+railway+station",
    partnerName: "Vokzal Chayxona MCHJ",
    color: "#e0883c",
    isDemo: true,
    active: true,
  },
  {
    id: "loc_3",
    slug: "siyob-bazaar",
    name: "BagDrop — Siyob Bazaar",
    city: "Samarkand",
    address: "Main entrance of Siyob Bazaar",
    distanceLabel: "At the bazaar entrance",
    description:
      "Drop your bags before browsing the largest and busiest bazaar in Samarkand. Small counter, ask for BagDrop at the fruit stalls entrance.",
    pricePerBagPerDay: 28000,
    currency: "UZS",
    capacity: 20,
    availableBags: 6,
    maxBagsPerBooking: 4,
    hours: { open: "07:00", close: "20:00" },
    amenities: ["Verified partner", "Easy access"],
    lat: 39.6608,
    lng: 66.9793,
    googleMapsUrl: "https://maps.google.com/?q=Siyob+Bazaar+Samarkand",
    yandexMapsUrl: "https://yandex.com/maps/?text=Siyob+Bazaar+Samarkand",
    partnerName: "Siyob Bozori Xizmat",
    color: "#8a5a3b",
    isDemo: true,
    active: true,
  },
  {
    id: "loc_4",
    slug: "shah-i-zinda",
    name: "BagDrop — Shah-i-Zinda",
    city: "Samarkand",
    address: "Near Shah-i-Zinda necropolis",
    distanceLabel: "150m from the entrance",
    description:
      "A small partner café right outside the entrance to Shah-i-Zinda — a quiet, shaded spot to leave bags before the walk up.",
    pricePerBagPerDay: 25000,
    currency: "UZS",
    capacity: 15,
    availableBags: 15,
    maxBagsPerBooking: 4,
    hours: { open: "08:00", close: "19:00" },
    amenities: ["Verified partner", "Indoor storage"],
    lat: 39.6689,
    lng: 66.9903,
    googleMapsUrl: "https://maps.google.com/?q=Shah-i-Zinda+Samarkand",
    yandexMapsUrl: "https://yandex.com/maps/?text=Shah-i-Zinda+Samarkand",
    partnerName: "Zinda Cafe",
    color: "#3f7d6b",
    isDemo: true,
    active: true,
  },
  {
    id: "loc_5",
    slug: "gur-emir",
    name: "BagDrop — Gur-Emir",
    city: "Samarkand",
    address: "200m from Gur-Emir Mausoleum",
    distanceLabel: "200m from Gur-Emir",
    description: "A hostel lobby storage point, staffed all day, popular with backpackers.",
    pricePerBagPerDay: 30000,
    currency: "UZS",
    capacity: 25,
    availableBags: 11,
    maxBagsPerBooking: 6,
    hours: { open: "08:00", close: "21:00" },
    amenities: ["CCTV", "Verified partner", "QR check-in"],
    lat: 39.6497,
    lng: 66.9747,
    googleMapsUrl: "https://maps.google.com/?q=Gur-Emir+Samarkand",
    yandexMapsUrl: "https://yandex.com/maps/?text=Gur-Emir+Samarkand",
    partnerName: "Registan Hostel",
    color: "#6b4f8a",
    isDemo: true,
    active: true,
  },
  {
    id: "loc_6",
    slug: "university-boulevard",
    name: "BagDrop — University Boulevard",
    city: "Samarkand",
    address: "Samarkand University Boulevard",
    distanceLabel: "On the boulevard",
    description: "A coworking-space storage point, popular with longer-stay travelers and digital nomads.",
    pricePerBagPerDay: 22000,
    currency: "UZS",
    capacity: 18,
    availableBags: 2,
    maxBagsPerBooking: 3,
    hours: { open: "09:00", close: "21:00" },
    amenities: ["Verified partner", "Indoor storage"],
    lat: 39.6714,
    lng: 66.9599,
    googleMapsUrl: "https://maps.google.com/?q=Samarkand+University+Boulevard",
    yandexMapsUrl: "https://yandex.com/maps/?text=Samarkand+University+Boulevard",
    partnerName: "Nomad Hub Samarkand",
    color: "#2f6b5a",
    isDemo: true,
    active: true,
  },
];

export function getLocationBySlug(slug: string): Location | undefined {
  return LOCATIONS.find((l) => l.slug === slug);
}
